### ISSUE TITLE
doesnt work on other users message

### ISSUE THREAD

**Issue by curiositIy** [the-cord-plug/quick-delete-pc#2]
exactly what the title says, when i hold down backspace and try to delete someone's message it doesn't work

yes i have admin in the server

**Comment by jdadonut** [comment]
I'll look into this as soon as I have some time, likely around this weekend as I have a deadline this Thursday for some work I need to get done.

**Comment by MrZeroLord** [comment]
yes. please.
Its so sad that we have to delete them manually...
Would be amazing if that could get added.
